2019-09-24 12:02:57,235 ERROR: Exception on /reset_password_request [POST] [in C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Git\MicroBlog\app\routes.py", line 103, in reset_password_request
    send_password_reset_email(user)
  File "D:\Git\MicroBlog\app\email.py", line 17, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token))
  File "D:\Git\MicroBlog\app\email.py", line 10, in send_email
    mail.send(msg)
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "C:\Users\Katuhis\AppData\Local\Programs\Python\Python37-32\Lib\smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "C:\Users\Katuhis\AppData\Local\Programs\Python\Python37-32\Lib\smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "C:\Users\Katuhis\AppData\Local\Programs\Python\Python37-32\Lib\smtplib.py", line 307, in _get_socket
    self.source_address)
  File "C:\Users\Katuhis\AppData\Local\Programs\Python\Python37-32\Lib\socket.py", line 727, in create_connection
    raise err
  File "C:\Users\Katuhis\AppData\Local\Programs\Python\Python37-32\Lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение
2019-09-24 12:05:52,527 INFO: Microblog startup [in D:\Git\MicroBlog\app\__init__.py:48]
2019-09-24 12:06:03,112 ERROR: Exception on /reset_password_request [POST] [in C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Git\MicroBlog\app\routes.py", line 103, in reset_password_request
    send_password_reset_email(user)
  File "D:\Git\MicroBlog\app\email.py", line 17, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token))
  File "D:\Git\MicroBlog\app\email.py", line 10, in send_email
    mail.send(msg)
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask_mail.py", line 163, in configure_host
    host.starttls()
  File "C:\Users\Katuhis\AppData\Local\Programs\Python\Python37-32\Lib\smtplib.py", line 752, in starttls
    "STARTTLS extension not supported by server.")
smtplib.SMTPNotSupportedError: STARTTLS extension not supported by server.
2019-09-24 12:07:22,195 INFO: Microblog startup [in D:\Git\MicroBlog\app\__init__.py:48]
2019-09-24 12:07:35,842 ERROR: Exception on /reset_password_request [POST] [in C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Git\MicroBlog\app\routes.py", line 103, in reset_password_request
    send_password_reset_email(user)
  File "D:\Git\MicroBlog\app\email.py", line 17, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token))
  File "D:\Git\MicroBlog\app\email.py", line 10, in send_email
    mail.send(msg)
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask_mail.py", line 163, in configure_host
    host.starttls()
  File "C:\Users\Katuhis\AppData\Local\Programs\Python\Python37-32\Lib\smtplib.py", line 752, in starttls
    "STARTTLS extension not supported by server.")
smtplib.SMTPNotSupportedError: STARTTLS extension not supported by server.
2019-09-24 12:08:11,532 INFO: Microblog startup [in D:\Git\MicroBlog\app\__init__.py:48]
2019-09-24 12:08:21,375 ERROR: Exception on /reset_password_request [POST] [in C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Katuhis\.virtualenvs\MicroBlog-nqmslJ8v\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Git\MicroBlog\app\routes.py", line 103, in reset_password_request
    send_password_reset_email(user)
  File "D:\Git\MicroBlog\app\email.py", line 16, in send_password_reset_email
    text_body=render_template('email/reset_password.txt', user=user, token=token)#,
TypeError: send_email() missing 1 required positional argument: 'html_body'
2019-09-24 12:08:54,024 INFO: Microblog startup [in D:\Git\MicroBlog\app\__init__.py:48]
2019-09-24 12:09:07,652 INFO: Microblog startup [in D:\Git\MicroBlog\app\__init__.py:48]
2019-09-24 12:09:55,535 INFO: Microblog startup [in D:\Git\MicroBlog\app\__init__.py:48]
